name: PR Check
run-name: Check PR ${{ github.ref_name }}

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, edited, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github app token
        uses: wow-actions/use-app-token@v2
        id: app-token
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Check PR
        uses: Mozilla-Campus-Club-of-SLIIT/pr-check-action@dev
        with:
          token: ${{ steps.app-token.outputs.bot_token }}
          comment-author: ${{ steps.app-token.outputs.bot_name}}[bot]

